import pygame
from time import sleep
pygame.init()
window = pygame.display.set_mode((0,0), pygame.FULLSCREEN)
pygame.mixer.init()
pygame.mixer.music.load('horror.mp3')
pygame.mixer.music.play()
sleep(4)
pygame.mixer.music.load('ratsasan.mp3')
pygame.mixer.music.play()
sleep(3)
pygame.mixer.music.load('most.mp3')
pygame.mixer.music.play()
sleep(4)
image = pygame.image.load('dark.jpg')
window.blit(image, (0,0))
pygame.display.update()
sleep(1.5)
image = pygame.image.load('horror.jpg')
window.blit(image, (0,0))
pygame.display.update()
sleep(1.7)
image = pygame.image.load('rkZVbl.jpg')
window.blit(image, (0,0))
pygame.display.update()
sleep(1.8)
image = pygame.image.load('scr.jpg')
window.blit(image, (0,0))
pygame.display.update()
sleep(1.9)

